services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    s365_id_mapping.http_client:
        class: Symfony\Component\HttpClient\ScopingHttpClient
        factory: ['Symfony\Component\HttpClient\ScopingHttpClient', 'forBaseUri']
        arguments:
            $client: '@http_client'
            $baseUri: '%env(S365_ID_MAPPING_API_URL)%'
            $defaultOptions:
                timeout: 10
                retry_failed:
                    max_retries: 3
                    http_codes: [429, 500, 502, 503, 504]
                    methods: ['GET']
                    delay: 1000
                    multiplier: 2
                    jitter: 0.1

    Bash\S365IDMappingBundle\Domain\HttpClient\IdMappingClientInterface:
        alias: Bash\S365IDMappingBundle\Infrastructure\HttpClient\IdMappingClient

    Bash\S365IDMappingBundle\Infrastructure\HttpClient\IdMappingClient:
        arguments:
            $httpClient: '@s365_id_mapping.http_client'
        tags:
            - { name: monolog.logger, channel: s365_id_mapping }

    Bash\S365IDMappingBundle\Infrastructure\Symfony\Controller\:
        resource: '../../Infrastructure/Symfony/Controller/'
        public: true
        tags: ['controller.service_arguments']
