name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, mbstring, curl
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check Code Style
        run: composer cs-fix -- --dry-run --diff

      - name: Static Analysis (PHPStan)
        run: composer phpstan

      - name: Run Tests (PHPUnit)
        run: composer test
